export const ADD_COMMENT = 'ADD_COMMENT'
export const CAMPSITES_LOADING = 'CAMPSITE_LOADING'; //when campsite data is loading and waiting for data to come back after request to server
export const CAMPSITES_FAILED = 'CAMPSITES_FAILED'; //if no response, will inform store to show error message
export const ADD_CAMPSITES = 'ADD_CAMPSITES';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';
